### ISSUE TITLE
Create a rolling log file to prevent it from getting too big

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#12]
Create a rolling log file to prevent it from getting too big

Should be easy to implement once you are using SLF4J + logging framework

**Comment by kbbgl** [comment]
Added in version 2.0.14712 (currently on `features` branch) using logback (https://logback.qos.ch/manual/configuration.html).

Default log level is `info`.

To change log level, open `e2ewd.jar > logback.xml` and change section:
```
<root level="info"> <--------MODIFY LOG LEVEL - debug, info, warn, error
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE" />
    </root>
```
