### ISSUE TITLE
Add a configuration option to ignore and don't alert on "ElastiCube is processing and cannot be queried"

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#19]
Sometimes the Watchdog will alert with a WARNING! REST API test failed for ElastiCube, with a response code 200 and response body:
{
   "database": "...",
   **"details": "ElastiCube is processing and cannot be queried.",**
   "error": true,
   "server": "LocalHost",
   "type": "busy"
}

It would be great to have a config option that will prevent alerts on these cases
This could happen for example if trying to query during a build, so it could probably be treated as false-positive

**Comment by kbbgl** [comment]
Duplicate to #17
