### ISSUE TITLE
Upon receiving a response code 401 (empty body) or 404 (api not found) - stop the Watchdog, do not continue to test the other ElastiCubes

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#25]
It seems that whenever we are getting a response code of **401** (with an **empty response body**) or **404** (with a body of "**api not found**") for a **/jaql REST API test** of a specific ElastiCube, then all the following tests for the other ElastiCubes will also fail.
Therefore, in order to prevent the bloat of messages we are getting on our Slack channel, I suggest that once we receive such a response code we will stop the Watchdog and will not continue to test the additional ElastiCubes

**Comment by kbbgl** [comment]
Fixed in version 2.8.0
