### ISSUE TITLE
Verify that the Watchdog creates Full Process Dumps and NOT Mini Dumps

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#29]
I saw an .mht file, created by Microsoft Debug Diagnostics Analysis utility, for a .dmp file that was generated by the Watchdog, and it did NOT seem to include useful/meaningful info.

**Comment by kbbgl** [comment]
@nirzilbermansisense - This file was created by WER and not by the application.

To create dump files, I utilize [procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) with the following command:

`procdumpPath + " -accepteula -o -ma " + ELASTICUBE_PROCESS_NAME + " ecs_dump.dmp"`

Where the arguments:
`-o`  - overwrites an existing dump file.
`-ma` - **Write a dump file with all process memory. The default dump format only includes thread and handle information.**
