### ISSUE TITLE
Allow additional IP/host name

### ISSUE THREAD

**Issue by yeholerner** [kbbgl/e2ewd#30]
In multi deployments, it's likely that the server that is used is not under LocalHost but under an IP.
For example, the Build node will never be localhost on the front end.

Add an optional parameter to insert an additional IP.
Add an optional boolean if you wish to check localhost

**Comment by kbbgl** [comment]
@yeholerner - But in multi-server deployments the Sisense.ECMS service shouldn't be running on the web nodes so we can't run PSM with `serverAddress=QUERY_NODE_IP`. In addition, the purpose of the tool is to check the query service so why do we care about the build node in this case?
