### ISSUE TITLE
Languages capabilities

### ISSUE THREAD

**Issue by yeholerner** [kbbgl/e2ewd#36]
When there is a cube in a different language the watchdog fails.
Tested on french and Russian

**Comment by kbbgl** [comment]
Looks like the PSM returns the ElastiCube that has a Russian title with question marks:

`C:\tools\e2ewd>set sisense_psm=true&&psm ecs listcubes serverAddress=localhost`

```
 ■ Listing Cubes on localhost...
Cube Name [??????????] ID : [aHQQaPgQaQAQaNAQaPAQaNQQaQgQaMAQaOwQaOwQa] FarmPath [C:\ProgramData\SiSense\PrismServer\ElastiCubeData\aHQQaPgQaQAQaNAQaPAQaNQQaQgQaMAQaOwQaOwQa_2019-10-10_18-29-37] Status [RUNNING]
```

**Comment by kbbgl** [comment]
Issue with Sisense - https://jira.sisense.com/browse/SNS-20296

Closing.
