### ISSUE TITLE
mClient + ECubeMaster

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#4]
In the libs, could you please include mClient + ECubeMaster, instead of only mClient?
You can use this version:
https://confluence.sisense.com:8443/download/attachments/49185925/mclient%2B.zip?version=3&modificationDate=1543392553807&api=v2 
(taken from this confluence page: https://confluence.sisense.com:8443/display/support/mClient+query+runner)

**Comment by kbbgl** [comment]
Added in 1.1.91547.
