### ISSUE TITLE
When "iisRestart" and/or "ecsRestart" are enabled, the Watchdog should restart the relevant on ANY test failure (and not only on a specific test)

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#41]
When "iisRestart" and/or "ecsRestart" are enabled, the Watchdog should restart the relevant on ANY test failure (and not only on a specific test)

**Comment by nirzilbermansisense** [comment]
Here is an example for the REST API test failing, where we would want the Watchdog to restart the ECS (assuming "ecsRestart" is enabled):
![image](https://user-images.githubusercontent.com/42610561/70127826-73a66400-1684-11ea-86f0-936f9857bf34.png)

> ERROR tests.SisenseRESTAPIClient - Query failed for <ElastiCube> with code 200, error: JSONObject["values"] not found.

> WARN tests.MainTest - REST API test failed ElastiCube <ElastiCube> with response code 200, response body:
> {
>     "database": "<ElastiCube">,
>     "details": "Could not connect to net.tcp://localhost:812/AbacusQueryService. The connection lasted for a time span of <approximately 2 seconds>. TCP error code 10061: No connection could be made because the target machine actively refused it",
>     "error": true,
>     "server": "LocalHost",
>     "type": "com"
> }

**Comment by kbbgl** [comment]
Added in version 4.1.0
