### ISSUE TITLE
When no cubes running and the chosen one is in build mode - error

### ISSUE THREAD

**Issue by yeholerner** [kbbgl/e2ewd#48]
The cube that was chosen was building, so the test kept failing. once I started a different cube the test passed

05/01/2020 01:15:18.962 [main] INFO  cmd_ops.ElastiCubeRESTAPIClient - GET api/elasticubes/servers/LocalHost returned 20 ElastiCubes
05/01/2020 01:15:18.963 [main] INFO  tests.MainTest - No ElastiCubes in RUNNING mode.
05/01/2020 01:15:18.964 [main] INFO  tests.MainTest - Chosen default ElastiCube to start: AEPerformanceMetric
05/01/2020 01:15:18.973 [main] INFO  cmd_ops.CmdOperations - Starting ElastiCube AEPerformanceMetric
05/01/2020 01:15:19.505 [main] INFO  tests.MainTest - Retrying...

**Comment by kbbgl** [comment]
Fixed in 9.1.0. Should see a log:

```
14/01/2020 19:49:54.458 [main] INFO  tests.queryservice.ECSStateKeeper - ElastiCube 'a' is currently building and will not be added to list of available ElastiCubes.
14/01/2020 19:49:54.459 [main] INFO  tests.MainTest - No ElastiCubes in RUNNING mode.
14/01/2020 19:49:54.460 [main] INFO  tests.MainTest - Chosen default ElastiCube to start: Sample ECommerce
14/01/2020 19:49:54.462 [main] INFO  t.q.ElastiCubeRESTAPIClient - Starting ElastiCube Sample ECommerce from REST API...
14/01/2020 19:49:55.363 [main] INFO  tests.MainTest - API call to start ElastiCube Sample ECommerce responded with 200
```
