### ISSUE TITLE
Add configuration option to create process dump files for Elasticube.exe

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#5]
Please add a new configuration option "ecDump" (similar to "iisDump" and "ecsDump"), that will allow creating a process dump for ElastiCube.exe. 
These ElastiCube.exe process dump files will be very useful for analyzing complex issues.
The risk/downside here is that these process dump files could potentially reach a very large size.
Therefore, we should probably also monitor the free disk space, before creating a process dump file, and maybe also keep only the last dump file that is created, and avoid accumulation of them.

**Comment by kbbgl** [comment]
PowerShell command to extract PID:

```
Get-WmiObject Win32_Process -Filter "name = 'elasticube.exe'" | Select-Object ProcessId, CommandLine | where CommandLine -CMatch "mapi_port=50001" | Select-Object ProcessId -ExpandProperty ProcessId

# sample output: 
# 9148
```

**Comment by kbbgl** [comment]
Added in version 2.4.94524.

```
#in properties.config
ecDump=false
```

**Comment by kbbgl** [comment]
Dump will create 1 file only and overwrite any that are left over in the parent dir.
