### ISSUE TITLE
App doesn't exit properly if not able to get to LocalHost

### ISSUE THREAD

**Issue by yeholerner** [kbbgl/e2ewd#54]
As you can see issue with the response to get localhost
`	friendlyHostName:mdilubes.sisense.com
	}
19/01/2020 10:44:24.342 [main] DEBUG tests.MainTest - Initiating test...
19/01/2020 10:44:24.342 [main] DEBUG tests.MainTest - Executing pre-run test validations...
19/01/2020 10:44:24.342 [main] DEBUG file_ops.ResultFile - Deleting result file...
19/01/2020 10:44:24.343 [main] DEBUG file_ops.ResultFile - Result file exists.
19/01/2020 10:44:24.343 [main] DEBUG file_ops.ResultFile - Result file deleted.
19/01/2020 10:44:24.344 [main] DEBUG file_ops.ResultFile - Result file doesn't exist.
19/01/2020 10:44:24.345 [main] DEBUG file_ops.ResultFile - Created new result file in C:\Scripts\e2ewd\run\result.txt
19/01/2020 10:44:24.345 [main] INFO  tests.MainTest - Attempt number 1
19/01/2020 10:44:24.345 [main] INFO  tests.MainTest - 'runningRemotely=true'. Skipping rabbitmq health check...
19/01/2020 10:44:24.346 [main] INFO  tests.MainTest - Retrieving list of ElastiCubes...
19/01/2020 10:44:27.363 [main] DEBUG t.q.ElastiCubeRESTAPIClient - Executing REST API call to GET /getElastiCubes...
19/01/2020 10:44:27.364 [main] DEBUG t.q.ElastiCubeRESTAPIClient - Parsing response...
19/01/2020 10:44:27.372 [main] WARN  t.q.ElastiCubeRESTAPIClient - Bad GET request sent to '/api/elasticubes/servers/LocalHost'
19/01/2020 10:44:27.373 [main] DEBUG t.q.ElastiCubeRESTAPIClient - ?<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Request Error</title>
    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>
  </head>
  <body>
    <div id="content">
      <p class="heading1">Request Error</p>
      <p xmlns="">The server encountered an error processing the request. Please see the <a rel="help-page" href="http://172.31.20.90:14996/api/elasticubes/help">service help page</a> for constructing valid requests to the service. The exception message is 'Unknown error occurred'. See server logs for more details. The exception stack trace is: </p>
      <p>   at Prism.Web.Server.ElasticubesService.GetCubes(String serverAddress, String term, Int32 offset, Int32 count, String orderBy, String direction, Boolean metadataOnly, SearchCubeBy by)
   at Prism.Web.Server.ElasticubesService.GetCubes(String serverAddress, String term, Int32 offset, Int32 count, String orderBy, String direction, String cubeId)
   at SyncInvokeGetCubes(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)</p>
    </div>
  </body>
</html>
19/01/2020 10:44:27.377 [main] DEBUG t.q.ElastiCubeRESTAPIClient - Releasing REST API client connection...
19/01/2020 10:44:27.377 [main] DEBUG t.q.ElastiCubeRESTAPIClient - REST API client connection released.
19/01/2020 10:44:27.378 [main] DEBUG tests.queryservice.ECSStateKeeper - Created ECSStateKeeper instance
19/01/2020 10:44:27.378 [main] INFO  tests.MainTest - No ElastiCubes in RUNNING mode.`

**Comment by kbbgl** [comment]
Fixed in 9.1.1
