### ISSUE TITLE
Use MAL commands to test number of concurrent connections for each ElastiCube

### ISSUE THREAD

**Issue by nirzilbermansisense** [kbbgl/e2ewd#7]
Test if a specific ElastiCube has many concurrent connections, which could indicate a problem with it.
These are the MAL commands to run:

1. `c := status.count_clients();`
2. `io.print(c);`

**Comment by kbbgl** [comment]
@nirzilbermansisense - Was looking at implementing this and stumbled upon https://www.monetdb.org/Documentation/Cookbooks/SQLrecipes/monitor

Looks like really useful information.

**Comment by kbbgl** [comment]
Added in version 2.2.57811.

`System.out.println("Number of connections for ElastiCube " + elastiCube.getName() + " : "+ CmdOperations.getInstance().getMonetDBConcurrentConnections(elastiCube));`
